services:
  - type: web
    name: calendar-api
    env: python
    plan: starter  # Upgraded from free for production monitoring
    buildCommand: |
      pip install --upgrade pip && 
      pip install -r requirements.txt &&
      pip install prometheus-client==0.19.0 psutil==5.9.6 gunicorn==21.2.0
    startCommand: |
      mkdir -p logs cache &&
      gunicorn --bind 0.0.0.0:$PORT --workers 2 --worker-class uvicorn.workers.UvicornWorker --access-logfile logs/access.log --error-logfile logs/error.log --log-level info api.app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_DIR
        value: logs
      - key: ENABLE_METRICS
        value: true
      - key: CACHE_TTL_HOURS
        value: 24
      - key: RATE_LIMIT_PER_MINUTE
        value: 60
      - key: RATE_LIMIT_PER_HOUR
        value: 1000
      - key: HEALTH_CHECK_INTERVAL
        value: 30
      - key: PERFORMANCE_MONITORING
        value: true
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /healthz